// Generated by CoffeeScript 1.3.1
(function() {
  var _this = this;

  chrome.browserAction.onClicked.addListener(function(tab) {
    if (_this.available) {
      return chrome.tabs.create({
        url: "http://localhost:3000"
      });
    } else {
      return chrome.tabs.create({
        url: "options.html"
      });
    }
  });

}).call(this);
